<br /><br />
<div id="view-content">
	<p><b> Managecategory </b></p>
	<?php 		
		$form = $this -> form;
		echo $form;
	?>
	
	<!--<form action="<?php echo $form -> getAction()?>" method="<?php echo $form -> getMethod()?>" enctype="<?php echo $form -> getEnctype()?>" name = "frmCategory">
		<table border="1">
			<tr>
				<td>Manage Category</td>
			</tr>
			<tr>
				<td>Category Name:</td>
				<td><input type="text" name ="categoryName" id="CategoryName" value = 'Art'></td>
			</tr>
			<tr>
				<td>Category Description:</td>
				<td><input type="text" name ="categoryDescription" id="categoryDescription" value = 'thangvx87'></td>
			</tr>
			<tr>
				<td>Category Status:</td>
				<td><select  name ="categoryStatus">
					  <option value="0">0</option>
					  <option value="1">1</option>
					  <option value="2">2</option>
					</select>
				</td>
			</tr>
			<tr>
				<td>
					<input type="submit" name="Submit" value="SUBMIT">
					<input type="reset" name="Reset" value="RESET">
				</td>
			</tr>
		</table>
	</form>
-->
</div>